// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9uatEQW66N3FTZiRal3QDBL6pgBGyAg',
    appId: '1:977763828916:web:0c06af71b09d4a929143e1',
    messagingSenderId: '977763828916',
    projectId: 'carbon-145bc',
    authDomain: 'carbon-145bc.firebaseapp.com',
    storageBucket: 'carbon-145bc.appspot.com',
    measurementId: 'G-S2X60ZN2FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHstQQxRA_ZtcES9HoYM9xDFcWU5nkMo',
    appId: '1:977763828916:android:e43346699166678e9143e1',
    messagingSenderId: '977763828916',
    projectId: 'carbon-145bc',
    storageBucket: 'carbon-145bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOzdAJaEE_uEmcJ8TAHCoFAT7AhZ6SpE',
    appId: '1:977763828916:ios:dc568936e5441b7f9143e1',
    messagingSenderId: '977763828916',
    projectId: 'carbon-145bc',
    storageBucket: 'carbon-145bc.appspot.com',
    iosBundleId: 'com.example.carbonery',
  );
}
